blog/urls.py
from django.urls import path
from blog.views import *
from blog.feeds import LatestEntriesFeed

app_name = 'blog'

urlpatterns = [
    path('', blog_view, name='index'),
    path('<int:pid>', blog_single,name='single'),
    path('category/<str:cat_name>',blog_view,name='category'),
    path('tag/<str:tag_name>',blog_view,name='tag'),
    path('author/<str:author_username>',blog_view,name='author'),
    path('search/',blog_search, name = 'search'),
    path('rss/feed/', LatestEntriesFeed()),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
import debug_toolbar

sitemaps = {
    'static': StaticViewSitemap,
    'blog' : BlogSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('website.urls')),
    path('blog/', include('blog.urls')),

    path('accounts/', include('accounts.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', include('robots.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('captcha/', include('captcha.urls')),
    
]
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from website.views import *

app_name = 'website'

urlpatterns = [
    path('', index_view, name='index'),
    path('about', about_view,name='about'),
    path('contact', contact_view,name='contact'),
    path('portfolio', portfolio_view,name='portfolio'),
    path('pricing', pricing_view,name='pricing'),
    path('services', services_view,name='services'),
    path('testimonials', testimonials_view,name='testimonials'),
    path('newsletter',newsletter_view,name='newsletter')
]

blog/models.py
# from ctypes.wintypes import tagMSG
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Post(models.Model):
    image = models.ImageField(upload_to = 'blog/',default = 'blog/default.jpg')
    author = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    title = models.CharField(max_length=255)
    content = models.TextField()
    tags = TaggableManager()
    category = models.ManyToManyField(Category)
    counted_views = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    login_require = models.BooleanField(default=False)
    published_date = models.DateTimeField(null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering =['-created_date']
        

    def __str__(self):
        return "{} - {}".format(self.title, self.id)

    def snippets(self):
        return self.content[:100]+'...'

    def get_absolute_url(self):
        return reverse('blog:single',kwargs={'pid':self.id})

class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    approved = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('created_date',)

    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from blog.models import Comment
from captcha.fields import CaptchaField

class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields =['post','name','subject','message','email']

blog/views.py
from django.shortcuts import render,get_object_or_404, redirect
from blog.models import Post,Comment
from django.core.paginator import PageNotAnInteger, Paginator, EmptyPage
from blog.forms import CommentForm
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.


def blog_view(request,**kwargs):
    posts = Post.objects.filter(status=1)
    if kwargs.get('cat_name') != None:
        posts = posts.filter(category__name = kwargs['cat_name'])
    if kwargs.get('author_username') != None:
        posts = posts.filter(author__username = kwargs['author_username'])
    if kwargs.get('tag_name') != None:
        posts = posts.filter(tags__name__in = [kwargs['tag_name']])

    posts = Paginator(posts,3)
    try:
        page_number = request.GET.get('page')
        posts = posts.get_page(page_number)
    except PageNotAnInteger:
        posts = posts.get_page(1)
    except EmptyPage:
        posts = posts.get_page(1)

    
    context = {'posts':posts}
    return render(request, 'blog/blog-home.html',context)



def blog_single(request,pid):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request,messages.SUCCESS,'your comment submitted')
        else:
            messages.add_message(request,messages.ERROR,'your comment did not submitted')

    posts = Post.objects.filter(status=True)
    post = get_object_or_404(posts,pk=pid)
    post.counted_views=post.counted_views+1
    post.save()

    if X := Post.objects.filter(status=True, id__lt=post.id)[0:1]:
        prev_post = get_object_or_404(X)
    else:
        prev_post = post 
    if Y := Post.objects.filter(status=True, id__gt=post.id).order_by('id')[0:1]:
        next_post = get_object_or_404(Y)
    else:
        next_post = post


    if not post.login_require:
        comments =Comment.objects.filter(post=post.id,approved=True)
        form = CommentForm()
        context = {'post':post,'comments':comments, 'form':form,'prev_post':prev_post,'next_post':next_post}
        return render(request,'blog/blog-single.html',context)
    else:
        return HttpResponseRedirect(reverse('accounts:login'))


def blog_category(request,cat_name):
    posts = Post.objects.filter(status=True)
    posts = posts.filter(category__name = cat_name)
    context = {'posts': posts}
    return render(request,'blog/blog-home.html', context)


def blog_search(request):
    posts = Post.objects.filter(status=1)
    if request.method == 'GET':
        if S:= request.GET.get('s'):
           posts = posts.filter(content__contains=S)
    context = {'posts': posts}
    return render(request,'blog/blog-home.html', context)

templates/blog/blog-categories.html
{% load static %}
<!-- start sidebar categories-->
<h3 class="sidebar-title">Categories</h3>
<div class="sidebar-item categories">
    <ul>
        {% for name,count in categories.items %}
        <li><a href="{% url 'blog:category' cat_name=name %}" class="d-flex justify-content-between">
            <P> {{ name }}</P>
            <span>{{ count }}</span></a>
        </li>
        {% endfor %}
    </ul>
</div>
<!-- End sidebar categories-->

templates/blog/blog-home.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}
{% load blog_tags %}

{% block content %}

  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section id="breadcrumbs" class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>Blog</h2>
          <ol>
            <li><a href="index.html">Home</a></li>
            <li>Blog</li>
          </ol>
        </div>

      </div>
    </section><!-- End Breadcrumbs -->

    <!-- ======= Blog Section ======= -->
    <section id="blog" class="blog">
      <div class="container" data-aos="fade-up">

        <div class="row">

          <div class="col-lg-8 entries">
            <!-- ======================================================= -->
            {% for post in posts %}
            <article class="entry">

              <div class="entry-img">
                <img src="{{post.image.url}}" alt="" class="img-fluid">
              </div>

              <h2 class="entry-title">
                <a href="/blog/{{post.id}}">{{post.title}}</a>
              </h2>

              <div class="entry-meta">
                <h5 class="bi bi-stack">

                  <!-- {{post.category.all|join:", " }} -->
                  {% for cat in post.category.all %}
                  <a href="{% url 'blog:category' cat_name=cat.name%}"> {{cat.name}} </a>
                    {% if not forloop.last %}, 
                    {% endif %}
                  {% endfor %}
                </h5>
                <ul>
                  <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a href="{% url 'blog:author' author_username=post.author.username %}">{{post.author.get_full_name}}</a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a href="#"><time >{{post.published_date|date:"Y-M-d"}}</time></a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i> <a href="#">{% comments_count post.id %} Comments</a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-eye-fill"></i> <a href="#">{{post.counted_views}} views</a></li>
                </ul>
              </div>

              <div class="entry-content">
                <p>
                  {{post.content|truncatewords:20|safe}}
                </p>
                <div class="read-more">
                  <a href="/blog/{{post.id}}">Read More</a>
                </div>
              </div>

            </article><!-- End blog entry -->

            {% endfor %}
            <!-- ======================================================= -->
            <div class="blog-pagination">
              <nav class="blog-pagination justify-content-center d-flex">
                  <!-- ========================================== -->
                  
                  <ul class="pagination">
                    {% if posts.has_previous %}
                    <li >
                      <a href="?page={{ posts.previous_page_number }}" class="page-link" aria-label="Previous">
                        <span aria-hidden="true">
                          <span class="lnr lnr-chevron-left">previous</span>
                        </span>
                      </a>
                    </li>
                    {% endif %}
        
                    {% for i in posts.paginator.page_range %}
                    {% if posts.number == i  %}
                      <li class="active"><a href="?page={{i}}" class="page-link">{{i}}</a></li>
                      {% else %}
                      <li  ><a href="?page={{i}}" class="page-link" >{{i}}</a></li>
                    {% endif %}
                    {% endfor %}
        
                    {% if posts.has_next %}
                    <li >
                      <a href="?page={{ posts.next_page_number }}" class="page-link" aria-label="Next">
                        <span aria-hidden="true">
                          <span class="lnr lnr-chevron-right">next</span>
                        </span>
                      </a>
                    </li>
                    {% endif %}
                  </ul>
                  <!-- ========================================== -->
                </nav>
            </div>

          </div><!-- End blog entries list -->

          <div class="col-lg-4">

            <div class="sidebar">

            <!-- ===================================================== -->

            {% include 'blog/blog-search.html' %}
            <!-- ===================================================== -->
              
              {% postcategories %}
            <!-- ===================================================== -->

              {% latestposts %}
            <!-- ===================================================== -->
            </div><!-- End sidebar -->

          </div><!-- End blog sidebar -->

        </div>

      </div>
    </section><!-- End Blog Section -->

  </main><!-- End #main -->

  {% endblock %}
  <!-- ======= Footer ======= -->  

templates/blog/blog-recent-posts.html
{% load humanize %}
{% load static %}
<!-- Start sidebar recent posts-->
<h3 class="sidebar-title">Recent Posts</h3>
<div class="sidebar-item recent-posts">
    {% for post in posts %}
    <div class="post-item clearfix">
        <img src="{{post.image.url}}" alt="">
        <h4><a href="{% url 'blog:single' pid=post.id  %}">{{post.title}}</a></h4>
        <p>{{post.published_date|naturaltime}}</p>
    </div>
    {% endfor%}



</div>
<!-- End sidebar recent posts-->

templates/blog/blog-search.html
{% load static %}
<!-- Start sidebar search form-->
<h3 class="sidebar-title">Search</h3>
<div class="sidebar-item search-form">
    <form class="search-form" action="{% url 'blog:search'  %}" method='get'>
        <input placeholder="Search Posts" name="s" type="text" >
        <button type="submit"><i class="bi bi-search"></i></button>
    </form>
</div>
<!-- End sidebar search form-->

templates/blog/blog-single.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}
{% load blog_tags %}

{% block content %}

  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section id="breadcrumbs" class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>Blog Single</h2>
          <ol>
            <li><a href="{% url 'website:index' %}">Home</a></li>
            <li><a href="{% url 'blog:index' %}">Blog</a></li>
            <li>Blog Single</li>
          </ol>
        </div>

      </div>
    </section><!-- End Breadcrumbs -->

    <!-- ======= Blog Single Section ======= -->
    <section id="blog" class="blog">
      <div class="container" data-aos="fade-up">

        <div class="row">

          <div class="col-lg-8 entries">

            <article class="entry entry-single">

              <div class="entry-img">
                <img src="{{post.image.url}}" alt="" class="img-fluid">
              </div>

              <h2 class="entry-title">
                <a href="/blog/{{post.id}}">{{post.title}}</a>
              </h2>

              <div class="entry-meta">
                <h5 class="bi bi-stack">

                  {{post.category.all|join:", " }}
                </h5>
                <ul>
                  <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a href="{% url 'blog:author' author_username=post.author.username %}">{{post.author.get_full_name}}</a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a href="#"><time >{{post.published_date|date:"Y-M-d"}}</time></a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i> <a href="#">{{comments|length}} Comments</a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-eye-fill"></i> <a href="#">{{post.counted_views}} views</a></li>
                </ul>
              </div>

              <div class="entry-content">
                
                <p>
                  {{post.content|safe}}
                </p>
                

                               

              </div>

              
            </article><!-- End blog entry -->
           <!-- ========================================================== -->
           <div class="navigation-area">
            <div class="row">
              <div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
                <div class="thumb">
                  <a href="#"><img class="img-fluid" src="{{prev_post.image.url}}" alt="" width="120"></a>
                </div>
                <div class="arrow">
                  <a href="#"><span class="lnr text-white lnr-arrow-left"></span></a>
                </div>
                <div class="detials">
                  <p>Prev Post</p>
                  <a href="/blog/{{prev_post.id}}"><h4>{{prev_post.title}}</h4></a>
                </div>
              </div>
              <div class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
                <div class="detials">
                  <p>Next Post</p>
                  <a href="/blog/{{next_post.id}}"><h4>{{next_post.title}}</h4></a>
                </div>
                <div class="arrow">
                  <a href="#"><span class="lnr text-white lnr-arrow-right"></span></a>
                </div>
                <div class="sidebar-title">
                  <a href="#"><img class="img-fluid" src="{{next_post.image.url}}" alt="" width="120" ></a>
                </div>                    
              </div>                  
            </div>
          </div>
          <br>
          <br>
          <!-- ========================================================== -->



            <div class="blog-comments">

              <h4 class="comments-count">{{ comments|length }} Comments</h4>

              <div id="comment-1" class="comment">
                {% for comment in comments %}
                <div class="d-flex">
                  <div class="comment-img"><img src="{% static 'img/blog/comments-1.jpg' %}" alt=""></div>
                  <div>
                    <h5><a href="">{{ comment.name}}</a>      </h5>
                    <time datetime="2020-01-01">{{post.created_date|naturaltime}}</time>
                    <p>
                      {{ comment.message}}
                    </p>
                  </div>
                </div>
                {% empty %}
                <p>Post your first comment here.</p>
                {% endfor %}
              </div><!-- End comment #1 -->



              <!-- ========================================================== -->
              <div class="reply-form">
                <h4>Leave a Message</h4>
                <p>Your email address will not be published. Required fields are marked * </p>
                <form method="post" action='{% url "blog:single" pid=post.id %}'>
                  {% csrf_token %}
                  <input type="hidden" name="post" value={{post.id}}>
                  {% if request.user.is_authenticated %}

                  <input type="hidden" name="name" value={{request.user.first_name}}>
                  <input type="hidden" name="email" value={{request.user.email}}>

                  {% else %}
                  
                  <div class="row">
                    <div class="col-md-6 form-group">
                      <input name="name" type="text" class="form-control" placeholder="Your Name*">
                    </div>
                    <div class="col-md-6 form-group">
                      <input name="email" type="email" class="form-control" placeholder="Your Email*">
                    </div>
                  </div>

                  {% endif %}
                  <div class="row">
                    <div class="col form-group">
                      <input name="subject" type="text" class="form-control" placeholder="subject">
                    </div>
                  </div>
                  <div class="row">
                    <div class="col form-group">
                      <textarea name="message" class="form-control" placeholder="Your Comment*"></textarea>
                    </div>
                  </div>
                  <button type="submit" class="btn btn-primary">Post Comment</button>

                  {% if messages %}
                {% for message in messages %}
                   <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}">{{ message|safe }}</div>
                {% endfor %}
                {% endif %}

                {% if form.errors %}
                  <div class="alert alert-error">
                   <h4>Please fix the following errors</h4>
                   <ul>
                     {% for field in form %}
                       {% if field.errors %}
                         {% for error in field.errors %}
                           <li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>
                         {% endfor %}
                       {% endif %}
                     {% endfor %}
                   </ul>
                   {% if form.non_field_errors %}
                     {{ form.non_field_errors }}
                   {% endif %}
                 </div>
                {% endif %}
    
                </form>

              </div>

            </div><!-- End blog comments -->

          </div><!-- End blog entries list -->

          <div class="col-lg-4">

            <div class="sidebar">

            <!-- ===================================================== -->

            {% include 'blog/blog-search.html' %}
            <!-- ===================================================== -->
              
            {% postcategories %}
            <!-- ===================================================== -->

            {% latestposts %}
            <!-- ===================================================== -->
            
            {% include 'blog/blog-tags.html' %}
            <!-- ===================================================== -->

            {% include 'blog/blog-writer.html' %}
            <!-- ===================================================== -->
            </div><!-- End sidebar -->

          </div><!-- End blog sidebar -->

        </div>

      </div>
    </section><!-- End Blog Single Section -->

  </main><!-- End #main -->

  {% endblock %}
  <!-- ======= Footer ======= -->  

templates/blog/blog-tags.html
{% load static %}
<!-- Start sidebar tags-->
<h3 class="sidebar-title">Tags</h3>
<div class="sidebar-item tags">
    <ul>
        {% for tag in post.tags.all %}
        <li>
            <a href="{% url 'blog:tag' tag_name=tag.name %}">{{ tag.name }}</a>
        </li>
        {% endfor %}
    </ul>
</div>
<!-- End sidebar tags-->

templates/blog/blog-writer.html
{% load static %}
<!-- Start blog author bio -->
<div class="blog-author d-flex align-items-center">
    <h5>{{post.author.get_full_name}}
        <div class="social-links">
            <a href="https://twitter.com/frankoamin" class="twitter"><i class="bx bxl-twitter"></i></a>
            <a href="https://www.facebook.com/amin.franko" class="facebook"><i class="bx bxl-facebook"></i></a>
            <a href="https://www.instagram.com/aminfranko/" class="instagram"><i class="bx bxl-instagram"></i></a>
        </div>
        <img src="{% static 'img/blog/blog-author.jpg' %}" class="rounded-circle float-left" alt="">
    </h5>

    <div>
        <p>
            Growing up in Karaj, he has a master's degree in applied mathematics from Tarbiat Modares University in Tehran, and is active in the field of telecommunications and mobile phones, and has a master's degree in product field at RighTel Communication Services Company.
        </p>
    </div>
</div><!-- End blog author bio -->

templates/blog/blog.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}
{% load blog_tags %}

{% block content %}

  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <ol>
          <li><a href="index.html">Home</a></li>
          <li>Blog</li>
        </ol>
        <h2>Blog</h2>

      </div>
    </section><!-- End Breadcrumbs -->

    <!-- ======= Blog Section ======= -->
    <section id="blog" class="blog">
      <div class="container" data-aos="fade-up">

        <div class="row">

          <div class="col-lg-8 entries">

            <article class="entry">
            <!-- ======================================================= -->
            {% for post in posts %}

              <div class="entry-img">
                <img src="{{post.image.url}}" alt="" class="img-fluid">
              </div>

              <h2 class="entry-title">
                <a href="/blog/{{post.id}}">{{post.title}}</a>
              </h2>

              <div class="entry-meta">
                <h5 class="bi bi-stack">

                  <!-- {{post.category.all|join:", " }} -->
                  {% for cat in post.category.all %}
                  <a href="{% url 'blog:category' cat_name=cat.name%}"> {{cat.name}} </a>
                    {% if not forloop.last %}, 
                    {% endif %}
                  {% endfor %}
                </h5>
                <ul>
                  <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a href="{% url 'blog:author' author_username=post.author.username %}">{{post.author.get_full_name}}</a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a href="#"><time >{{post.published_date|date:"Y-M-d"}}</time></a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i> <a href="#">{% comments_count post.id %} Comments</a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-eye-fill"></i> <a href="#">{{post.counted_views}} views</a></li>
                </ul>
              </div>

              <div class="entry-content">
                <p>
                  {{post.content|truncatewords:20|safe}}
                </p>
                <div class="read-more">
                  <a href="/blog/{{post.id}}">بیشتر بخوانید</a>
                </div>
              </div>

            </article><!-- End blog entry -->

            {% endfor %}
            <!-- ======================================================= -->
            <div class="blog-pagination">
              <ul class="justify-content-center">
                <li><a href="#">1</a></li>
                <li class="active"><a href="#">2</a></li>
                <li><a href="#">3</a></li>
              </ul>
            </div>

          </div><!-- End blog entries list -->

          <div class="col-lg-4"> 

            <div class="sidebar">

              <h3 class="sidebar-title">جستجو</h3>
              <div class="sidebar-item search-form">
                <form action="">
                  <input type="text">
                  <button type="submit"><i class="bi bi-search"></i></button>
                </form>
              </div><!-- End sidebar search formn-->

              <h3 class="sidebar-title">دسته بندی ها</h3>
              <div class="sidebar-item categories">
                <ul>
                  <li><a href="#">General <span>(25)</span></a></li>
                  <li><a href="#">Lifestyle <span>(12)</span></a></li>
                  <li><a href="#">Travel <span>(5)</span></a></li>
                  <li><a href="#">Design <span>(22)</span></a></li>
                  <li><a href="#">Creative <span>(8)</span></a></li>
                  <li><a href="#">Educaion <span>(14)</span></a></li>
                </ul>
              </div><!-- End sidebar categories-->

              <h3 class="sidebar-title">پست های اخیر</h3>
              <div class="sidebar-item recent-posts">
                <div class="post-item clearfix">
                  <img src="assets/img/blog/blog-recent-1.jpg" alt="">
                  <h4><a href="blog-single.html">Nihil blanditiis at in nihil autem</a></h4>
                  <time datetime="2020-01-01">Jan 1, 2020</time>
                </div>

                <div class="post-item clearfix">
                  <img src="assets/img/blog/blog-recent-2.jpg" alt="">
                  <h4><a href="blog-single.html">Quidem autem et impedit</a></h4>
                  <time datetime="2020-01-01">Jan 1, 2020</time>
                </div>

                <div class="post-item clearfix">
                  <img src="assets/img/blog/blog-recent-3.jpg" alt="">
                  <h4><a href="blog-single.html">Id quia et et ut maxime similique occaecati ut</a></h4>
                  <time datetime="2020-01-01">Jan 1, 2020</time>
                </div>

                <div class="post-item clearfix">
                  <img src="assets/img/blog/blog-recent-4.jpg" alt="">
                  <h4><a href="blog-single.html">Laborum corporis quo dara net para</a></h4>
                  <time datetime="2020-01-01">Jan 1, 2020</time>
                </div>

                <div class="post-item clearfix">
                  <img src="assets/img/blog/blog-recent-5.jpg" alt="">
                  <h4><a href="blog-single.html">Et dolores corrupti quae illo quod dolor</a></h4>
                  <time datetime="2020-01-01">Jan 1, 2020</time>
                </div>

              </div><!-- End sidebar recent posts-->

              <h3 class="sidebar-title">Tags</h3>
              <div class="sidebar-item tags">
                <ul>
                  <li><a href="#">App</a></li>
                  <li><a href="#">IT</a></li>
                  <li><a href="#">Business</a></li>
                  <li><a href="#">Mac</a></li>
                  <li><a href="#">Design</a></li>
                  <li><a href="#">Office</a></li>
                  <li><a href="#">Creative</a></li>
                  <li><a href="#">Studio</a></li>
                  <li><a href="#">Smart</a></li>
                  <li><a href="#">Tips</a></li>
                  <li><a href="#">Marketing</a></li>
                </ul>
              </div><!-- End sidebar tags-->

            </div><!-- End sidebar -->

          </div><!-- End blog sidebar -->

        </div>

      </div>
    </section><!-- End Blog Section -->

  </main><!-- End #main -->

  {% endblock %}
  <!-- ======= Footer ======= -->  
 